name:                lp
version:             0.1.0.0
github:              "githubuser/lp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/hmac/lp>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- deriving-compat
- transformers
- megaparsec
- prettyprinter

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  lp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lp

tests:
  lp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lp
    - hspec
    - hspec-megaparsec
