name:                lp
version:             0.1.0.0
github:              "hmac/lp"
license:             BSD3
author:              "Harry Maclean"
maintainer:          "harryjmaclean@gmail.com"
copyright:           "2019 Harry Maclean"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/hmac/lp>

dependencies:
- base >= 4.7 && < 5
- recursion-schemes
- deriving-compat
- transformers
- megaparsec
- prettyprinter
- prettyprinter-ansi-terminal
- safe
- terminal-size

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wno-missing-pattern-synonym-signatures

executables:
  lp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lp
    - optparse-applicative

tests:
  lp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lp
    - hspec
    - hspec-megaparsec
